version: '3.7'

services:
  
  ftw-daily:
    container_name: ftw-daily
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/app/src:Z
      - ./public:/var/www/app/public:Z
    environment:
      - ENV=development
    stdin_open: true
    ports:
      - 3000:3000